### ISSUE TITLE
Ad-Hoc Recordings are only 60 minutes

### ISSUE THREAD

**Issue by vinraec** [Panopto/Panopto-RR-Light-Service-With-Installer#10]
Hello,

We were going through the documentation for this app located here: https://www.panopto.com/blog/introducing-the-panopto-on-air-light-for-classroom-and-auditorium-recording/ and saw that an ad-hoc recording is set to 60 minutes. Is that something that can be changed from the light service side or only controlled via Panopto.

Thanks,
vinraec

**Comment by hohno-panopto** [comment]
This is determined by Panopto server side and no control light service or we don't have site setting to change that value as of today.
