### ISSUE TITLE
Installing before the Remote Recorder causes a non-descriptive install failure

### ISSUE THREAD

**Issue by derek-se** [Panopto/Panopto-RR-Light-Service-With-Installer#11]
When installing this service before the Remote Recorder is installed, the installer will fail with a message saying that it does not have permissions to start the service. 

#### To repro: 
With no RR installed, install the Light Service. The installer will fail to start the service with a useless message and no event log entries pointing to what's wrong

**Comment by hohno-panopto** [comment]
This is being tracked Panopto's internal bug database. TFS-50778. Closing.
