### ISSUE TITLE
Install issues on Win7

### ISSUE THREAD

**Issue by JasonMeyerICS** [Panopto/Panopto-RR-Light-Service-With-Installer#18]
Having an install error on a new install.

![Capture](https://user-images.githubusercontent.com/35506418/59947462-2b6eee80-9422-11e9-8a0d-2737ddb88abc.PNG)

**Comment by hohno-panopto** [comment]
I am sorry we did not respond this post. Because the support to Windows 7 has ended, I am closing this issue at this time. Please open a new issue if you experience the same issue in Windows 10.
