### ISSUE TITLE
webcast and pause

### ISSUE THREAD

**Issue by btb** [Panopto/Panopto-RR-Light-Service-With-Installer#6]
We noticed that the pause action does not work on webcasts. The RR tray icon appears to be webcast-aware and will not show a "pause" option if the current recording is a webcast. 

However, there doesn't appear to be any code here to differentiate between webcast and non-webcast recordings. Could that be added to the data returned by RemoteRecorderAPI's GetCurrentState() and GetNextRecording()?

**Comment by hohno-panopto** [comment]
This is fixed by https://github.com/Panopto/Panopto-RR-Light-Service-With-Installer/commit/c3e94e26da4572d7c1aa9dcd3ec153de460b37ff
